### ISSUE TITLE
useResizeDetector returns width = undefined using forwardRef 

### ISSUE THREAD

**Issue by baphony** [maslianok/react-resize-detector#238] opened 2023-03-10 16:38 UTC
**Using useResizeDectector in the parent for the child doesn't work as expected (using forwardRef):**

```jsx
import React, {forwardRef} from 'react';
import {useResizeDetector} from 'react-resize-detector';

const Child = forwardRef(({ width }, ref) => {
    return <div ref={ref}>Child ${width}</div>;
});

const Parent = (displayChild = false) => {
    const {width, ref} = useResizeDetector<HTMLDivElement>();
    console.log({width});

    return displayChild ? <Child ref={ref} width={width} /> : <div ref={ref}>Parent ${ width }</div>;
};

<Parent /> // Will return the width of the div
<Parent displayChild /> // Will return width = undefined
```

**Using useResizeDectector directly in the child works as expected:**

```jsx
import React, {forwardRef} from 'react';
import {useResizeDetector} from 'react-resize-detector';

const Child = () => {
    const {width, ref} = useResizeDetector<HTMLDivElement>();
    console.log({width});
    return <div ref={ref}>Child ${ width }</div>;
};

const Parent = (displayChild = false) => {
    const {width, ref} = useResizeDetector<HTMLDivElement>();
    console.log({width});

    return displayChild ? <Child /> : <div ref={ref}>Parent ${ width }</div>;
};

<Parent /> // Will return the width of the div
<Parent displayChild /> // Will return the width of the div
```

**Comment by baphony** [comment] 2023-03-10 16:41
Styles on the parent div:
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        margin: '8px',

Styles on the child:
        margin: '8px',
        borderRadius: '4px',
        marginBottom: '0px',
        padding: '8px 8px',
        paddingTop: '4px',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        minHeight: '0px',
        cursor: 'pointer'

**Comment by baphony** [comment] 2023-03-10 16:43
I tried with react-resize-detector v7 and v8, I get the same result

**Comment by snelsi** [comment] 2023-03-10 16:51
Looks like a duplicate of #178.

When `resizeObserver` is created, `ref` is `undefined`.
When `ref` actually mounts, it doesn't trigger a rerender of the `resizeObserver` effect.

Some people say adding those options might help:
```
{
  refreshMode: 'debounce',
  refreshRate: 300,
  refreshOptions: { trailing: true },
}
```

**Comment by baphony** [comment] 2023-03-13 09:37
Yes, I have a condition before too, so it looks like it's a duplicate, my code looks more like this:
```jsx
const Parent = (displayChild = false) => {
    const {width, ref} = useResizeDetector<HTMLDivElement>();
    console.log({width});

    if (something) {
        return null;
    }

    return displayChild ? <Child /> : <div ref={ref}>Child</div>;
};
```

**Comment by baphony** [comment] 2023-03-13 09:40
But it does work for the Parent even with the condition, only the Child component is affected by this bug

**Comment by baphony** [comment] 2023-03-15 12:25
Doing this fix the issue, thanks @snelsi and @barbalex! 👍 
```jsx
    const { width, height, ref } = useResizeDetector<HTMLDivElement>({ refreshOptions: { trailing: true } });
```
Shouldn't this be the default value?
And eventually create a "performance" section in the README file to suggest to disable it if there is no conditional rendering?

**Comment by snelsi** [comment] 2023-03-15 12:54
It's not a proper fix for the problem. `refreshOptions` can't detect changes in the `targetRef`.

A proper solution would probably mean storing `ref` in the `useState` and passing a callback function to the `ref` to trigger an observer's `useEffect` update whenever the target element is changed.

**Comment by barbalex** [comment] 2023-03-15 12:58
By the way: as container queries now work in all desktop browsers (https://caniuse.com/css-container-queries), I have removed most of my usage of react-resize-detect. Anything you can use the platform for is a definite win.

**Comment by maslianok** [comment] 2023-04-08 18:45
@baphony v9.0 should fix the issue. Now you should be able to safely remove `refreshMode` and `refreshRate` props.

@barbalex Great advice! I haven't heard about this feature. I even added this to Readme https://github.com/maslianok/react-resize-detector#do-you-really-need-this-library

**Closed by maslianok** 2023-04-08 18:45 UTC

**Comment by baphony** [comment] 2023-04-11 07:16
Great, many thanks!
