### ISSUE TITLE
useResizeDetector targetRef cannot be null TS2322

### ISSUE THREAD

**Issue by djswilly** [maslianok/react-resize-detector#233] opened 2023-02-17 01:25 UTC
Hi,

After the update to v8 we can no longer use the `targetRef` prop of `useResizeDetector` without TypeScript errors:
```
TS2322: Type 'MutableRefObject<HTMLDivElement | null>' is not assignable to type 'MutableRefObject<HTMLElement>'.
  Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
```
I'm not sure it's possible to use `useRef` for an HTML element without it possibly being null. Is this an issue with the type definition? If not, could you please provide an example of how I can declare and pass a `targetRef` to `useResizeDetector` in v8?

**Comment by snelsi** [comment] 2023-02-17 06:01
I guess you are using `strict: true` + `strictNullChecks : true`?

I think the problem is that we declare types as `React.MutableRefObject`, but when you add `null` as a default value to the ref it becomes regular `React.RefObject`.

We might try to fix this in a new minor release.
In the meantime, you can add `as` to the `targetRef` to overcome the issue:

```ts
 const targetRef = useRef<HTMLDivElement>(null);

 useResizeDetector({
   targetRef: targetRef as React.MutableRefObject<HTMLDivElement>
 });
```

As a side note, right now you can't pass conditional `null` ref to the `targetRef`, because it can cause #178

**Comment by djswilly** [comment] 2023-02-17 09:16
> I guess you are using `strict: true` + `strictNullChecks : true`?

Yes, we are using `strict: true`. No problems, thanks for the response!

**Comment by snelsi** [comment] 2023-02-18 13:48
@djswilly 
Should be fixed in v8.0.4.
Please, check if you experience any issues in the latest version

**Comment by snelsi** [comment] 2023-02-21 18:05
Closing this ticket for now. Feel free to reopen if you have any TS issues in the latest release

**Closed by snelsi** 2023-02-21 18:05 UTC
Labels: bug, enhancement, help wanted, typescript

**Comment by djswilly** [comment] 2023-02-22 01:46
Sorry for the delayed response, no issues in the latest version. Thanks for your help!
