### ISSUE TITLE
No measuring on lazy imported component

### ISSUE THREAD

**Issue by lexanth** [maslianok/react-resize-detector#176] opened 2021-08-11 11:16 UTC
https://codesandbox.io/s/charming-lewin-6rnvj?file=/src/App.js

`React.lazy` automatically forwards refs, so it should be fine to just wrap a component and still get the ref.

However, `react-resize-detector` doesn't get the delayed ref, because it isn't present by the time the `useEffect` hook is rerun. `ref.current` in the `useEffect` dependencies doesn't do anything because of the way it's mutated without triggering a rerender.

I've seen other implementations which always return callback refs wrapped around a ref object to work around this.

I suspect this would be the case with any component which doesn't attach the ref straight away.

**Comment by maslianok** [comment] 2021-08-11 14:13
Hi @lexanth 

Thanks for reporting this issue and for providing a code snippet.  
Spent some time trying to fix the problem and failed.

The problem is that `ref` is undefined during the initial render and then it gets silently assigned a value. The library needs to be notified somehow. Usually it happens through rerender.

btw, [we have `useEffect`](https://github.com/maslianok/react-resize-detector/blob/master/src/useResizeDetector.ts#L74) that is listening for `ref.currrent` changes, but, for some reason, it doesn't trigger :(

**Comment by lexanth** [comment] 2021-08-11 15:32
Yeah the `useEffect` won't receive the `ref.current` change because mutating `ref.current` doesn't trigger a rerender (so doesn't trigger the effect again). Basically the issue is that the `ref` isn't set by the time the `useEffect` runs. By the way, the hooks ESLint plugin warns that `ref.current` in the dependencies array doesn't work.

The solution would be to use a callback ref rather than a mutable ref object - then you can trigger the `ResizeObserver` creation when the callback is called, rather than depending on the ref's value having been assigned by the time the `useEffect` runs. But it's a reasonably big change!

For anyone else finding this (and for ideas on the fix!), these alternatives don't have the same issue (but have different APIs, other trade-offs etc)
* https://github.com/pbr1111/use-resize-observer
* https://github.com/ZeeCoder/use-resize-observer

**Comment by whplh** [comment] 2021-08-21 11:34
Just checked. Using a "callback ref" proposed in [old PR](https://github.com/maslianok/react-resize-detector/pull/136/commits/e6b42954843b1e9023149adb41475cb85c770551) would still solve the issue.
Relates to [prev issue](https://github.com/maslianok/react-resize-detector/pull/136)
You can also still see the bug on the intial render for the delayed component in [updated demo](https://codesandbox.io/s/material-demo-forked-iyng4?file=/demo.js)

**Comment by whplh** [comment] 2021-08-21 12:17
@lexanth  Which lib did you end up using?
I was curious about "use-resize-observer". It seems to support a "targetRef". (But [nope](https://codesandbox.io/s/use-resize-oberver-hopn7?file=/demo.js:426-433) =). 
Merging callbacks ([e.g](https://github.com/ZeeCoder/use-resize-observer#getting-the-raw-element-from-the-default-refcallback)) looks like a good idea if you need to support a "targetRef")

**Comment by maslianok** [comment] 2023-01-17 21:23
Closing the issues with no comments in the past year.

To the participants:
If you found a workaround or somehow fixed it - let me know. If you ended up using another library - feel free to mention it here

**Closed by maslianok** 2023-01-17 21:23 UTC
